// Regenerates src/tables.ts from the reference implementation's data tables:
//   LOGBOOK_REF=/path/to/clone/of/bighydro/logbook node scripts/make-tables.mjs
// The tables are data, not code: logbook/tables/airports.csv is OurAirports' large airports with
// scheduled service (public domain) with an IANA zone per row, and logbook/tables/zones.csv is the
// zone database's zone.tab (public domain), zone to ISO 3166-1 alpha-2 country. RFC 0013 rule 5 names
// the airports table as the one a reader looks airports up in, so both implementations carry the same
// rows and agree on the nearest airport, its city and its country. Never edit src/tables.ts by hand.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ref = process.env.LOGBOOK_REF;
if (!ref) {
  process.stderr.write("usage: LOGBOOK_REF=<clone> node scripts/make-tables.mjs\n");
  process.exit(2);
}
const here = dirname(fileURLToPath(import.meta.url));

/** RFC 4180 rows of a CSV text: quoted fields may hold commas. Comment lines (`#`) are skipped. */
function rows(text) {
  const out = [];
  for (const line of text.split(/\r?\n/)) {
    if (line === "" || line.startsWith("#")) continue;
    const fields = [];
    let field = "";
    let quoted = false;
    for (let i = 0; i < line.length; i++) {
      const ch = line[i];
      if (quoted) {
        if (ch === '"' && line[i + 1] === '"') {
          field += '"';
          i++;
        } else if (ch === '"') quoted = false;
        else field += ch;
      } else if (ch === '"') quoted = true;
      else if (ch === ",") {
        fields.push(field);
        field = "";
      } else field += ch;
    }
    fields.push(field);
    out.push(fields);
  }
  return out;
}

const airports = rows(readFileSync(join(ref, "logbook", "tables", "airports.csv"), "utf-8"));
const zones = rows(readFileSync(join(ref, "logbook", "tables", "zones.csv"), "utf-8"));
const aHeader = airports.shift().join(",");
const zHeader = zones.shift().join(",");
if (aHeader !== "iata,icao,name,lat,lon,tz,municipality,type" || zHeader !== "zone,country") {
  throw new Error(`unexpected columns: ${aHeader} / ${zHeader}`);
}

const airportRows = airports
  .map(
    (r) =>
      `  [${JSON.stringify(r[0])}, ${JSON.stringify(r[1])}, ${JSON.stringify(r[2])}, ${r[3]}, ${r[4]}, ${JSON.stringify(r[5])}, ${JSON.stringify(r[6])}, ${JSON.stringify(r[7])}],`,
  )
  .join("\n");
const zoneRows = zones
  .map((r) => `  [${JSON.stringify(r[0])}, ${JSON.stringify(r[1])}],`)
  .join("\n");

const out = `// Generated by scripts/make-tables.mjs from the reference implementation's data tables; never edit by hand.
// airports: OurAirports (public domain), the large airports with scheduled service, with the IANA zone
// the reference assigns each (RFC 0013 rule 5). zones: the zone database's zone.tab (public domain).

/** \`[iata, icao, name, lat, lon, tz, municipality, type]\` */
export type AirportRow = [string, string, string, number, number, string, string, string];

export const AIRPORT_ROWS: AirportRow[] = [
${airportRows}
];

/** \`[zone, ISO 3166-1 alpha-2 country]\` */
export const ZONE_ROWS: [string, string][] = [
${zoneRows}
];
`;
writeFileSync(join(here, "..", "src", "tables.ts"), out, "utf-8");
process.stdout.write(`src/tables.ts: ${airports.length} airports, ${zones.length} zones\n`);
